# docker-compose up --build
version: '2.4'
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: angular_dev:v0.0.0
    environment:
      - SPEAK=hello
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/angularExample/src:/main/angularExample/src
      - ./frontend/angularExample/.browserslistrc:/main/angularExample/.browserslistrc
      - ./frontend/angularExample/.editorconfig:/main/angularExample/.editorconfig
      - ./frontend/angularExample/.gitignore:/main/angularExample/.gitignore
      - ./frontend/angularExample/angular.json:/main/angularExample/angular.json
      - ./frontend/angularExample/package.json:/main/angularExample/package.json
      - ./frontend/angularExample/tsconfig.app.json:/main/angularExample/tsconfig.app.json
      - ./frontend/angularExample/tsconfig.json:/main/angularExample/tsconfig.json
      - ./frontend/angularExample/tsconfig.spec.json:/main/angularExample/tsconfig.spec.json
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: flask_dev:v0.0.0
    environment:
      - SPEAK=yo
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/main
  
    